"""AXIAL_TEMPLATE_SHIFT_MODEL – variable BGF-Gewindetiefe.

Variable depth is generated by rigid axial translation of the validated
manufacturer template. Incremental manufacturer path remains unchanged.

Dies ist KEINE offizielle CERATIZIT-Variable-Depth-Formel aus dem PDF,
sondern das bewusst gewaehlte technische Modell des Generators.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional, Sequence

# Numerische Toleranz fuer Reserve-Invariante und Plausibilitaet
RESERVE_TOLERANCE = 1e-6
GEOMETRY_TOLERANCE = 1e-9

DEPTH_MODEL_NAME = "AXIAL_TEMPLATE_SHIFT_MODEL"


@dataclass(frozen=True)
class AxialTemplateShiftResult:
    """Ergebnis der starren axialen Template-Verschiebung."""

    ok: bool
    is_template: bool
    requested_thread_depth: float
    depth_delta: float
    mill_start_depth: float
    drill_depth: float
    deepest_milling_depth: float
    drill_reserve: float
    template_drill_reserve: float
    error: Optional[str] = None


def axial_increment_from_pass_iz(
    iz_entry: float,
    iz_thread: float,
    iz_exit: float,
) -> float:
    return abs(iz_entry) + abs(iz_thread) + abs(iz_exit)


def axial_increment_from_passes(passes: Sequence) -> float:
    """Maximale axiale Helix-Summe aus den Pass-Daten (IZ entry/thread/exit)."""
    if not passes:
        return 0.0
    return max(
        axial_increment_from_pass_iz(p.iz_entry, p.iz_thread, p.iz_exit) for p in passes
    )


def template_drill_reserve(
    template_mill_start_depth: float,
    template_drill_depth: float,
    axial_increment: float,
) -> float:
    deepest = template_mill_start_depth + axial_increment
    return template_drill_depth - deepest


def compute_axial_template_shift(
    *,
    requested_thread_depth: float,
    template_thread_depth: float,
    template_mill_start_depth: float,
    template_drill_depth: float,
    axial_increment: float,
    template_tolerance: float = 1e-6,
) -> AxialTemplateShiftResult:
    """Berechnet verschobene Bohr-/Fraestiefen.

    depth_delta = template_thread_depth - requested_thread_depth
    shifted_mill = template_mill_start - depth_delta
    shifted_drill = template_drill_depth - depth_delta

    Bei Template-Tiefe: exakte Herstellerwerte ohne Neuberechnung.
    """
    tpl_reserve = template_drill_reserve(
        template_mill_start_depth, template_drill_depth, axial_increment
    )

    if abs(requested_thread_depth - template_thread_depth) <= template_tolerance:
        deepest = template_mill_start_depth + axial_increment
        return AxialTemplateShiftResult(
            ok=True,
            is_template=True,
            requested_thread_depth=template_thread_depth,
            depth_delta=0.0,
            mill_start_depth=template_mill_start_depth,
            drill_depth=template_drill_depth,
            deepest_milling_depth=deepest,
            drill_reserve=tpl_reserve,
            template_drill_reserve=tpl_reserve,
        )

    # Nur kuerzere Gewinde: requested muss unter Template liegen
    if requested_thread_depth > template_thread_depth + template_tolerance:
        return AxialTemplateShiftResult(
            ok=False,
            is_template=False,
            requested_thread_depth=requested_thread_depth,
            depth_delta=template_thread_depth - requested_thread_depth,
            mill_start_depth=float("nan"),
            drill_depth=float("nan"),
            deepest_milling_depth=float("nan"),
            drill_reserve=float("nan"),
            template_drill_reserve=tpl_reserve,
            error=(
                f"Gewindetiefe {requested_thread_depth:.3f} mm liegt ueber dem "
                f"Hersteller-Template {template_thread_depth:.3f} mm. "
                "Axiale Template-Verschiebung gilt nur fuer kuerzere Gewinde."
            ),
        )

    depth_delta = template_thread_depth - requested_thread_depth
    mill = template_mill_start_depth - depth_delta
    drill = template_drill_depth - depth_delta
    deepest = mill + axial_increment
    reserve = drill - deepest

    if not math.isfinite(mill) or not math.isfinite(drill):
        return AxialTemplateShiftResult(
            ok=False,
            is_template=False,
            requested_thread_depth=requested_thread_depth,
            depth_delta=depth_delta,
            mill_start_depth=mill,
            drill_depth=drill,
            deepest_milling_depth=deepest,
            drill_reserve=reserve,
            template_drill_reserve=tpl_reserve,
            error="Berechnete Shift-Geometrie ist nicht endlich.",
        )

    if mill <= GEOMETRY_TOLERANCE or drill <= GEOMETRY_TOLERANCE:
        return AxialTemplateShiftResult(
            ok=False,
            is_template=False,
            requested_thread_depth=requested_thread_depth,
            depth_delta=depth_delta,
            mill_start_depth=mill,
            drill_depth=drill,
            deepest_milling_depth=deepest,
            drill_reserve=reserve,
            template_drill_reserve=tpl_reserve,
            error=(
                f"Unplausible Shift-Geometrie: Frässtart={mill:.4f} mm, "
                f"NC-Bohrtiefe={drill:.4f} mm (beide muessen > 0 sein)."
            ),
        )

    if not (drill > deepest + GEOMETRY_TOLERANCE):
        return AxialTemplateShiftResult(
            ok=False,
            is_template=False,
            requested_thread_depth=requested_thread_depth,
            depth_delta=depth_delta,
            mill_start_depth=mill,
            drill_depth=drill,
            deepest_milling_depth=deepest,
            drill_reserve=reserve,
            template_drill_reserve=tpl_reserve,
            error=(
                f"NC-Bohrtiefe {drill:.4f} mm muss tiefer liegen als die "
                f"tiefste Fraesposition {deepest:.4f} mm."
            ),
        )

    if abs(reserve - tpl_reserve) > RESERVE_TOLERANCE:
        return AxialTemplateShiftResult(
            ok=False,
            is_template=False,
            requested_thread_depth=requested_thread_depth,
            depth_delta=depth_delta,
            mill_start_depth=mill,
            drill_depth=drill,
            deepest_milling_depth=deepest,
            drill_reserve=reserve,
            template_drill_reserve=tpl_reserve,
            error=(
                f"Drill-Reserve {reserve:.6f} weicht von Template-Reserve "
                f"{tpl_reserve:.6f} ab (AXIAL_TEMPLATE_SHIFT_MODEL-Invariante)."
            ),
        )

    return AxialTemplateShiftResult(
        ok=True,
        is_template=False,
        requested_thread_depth=requested_thread_depth,
        depth_delta=depth_delta,
        mill_start_depth=mill,
        drill_depth=drill,
        deepest_milling_depth=deepest,
        drill_reserve=reserve,
        template_drill_reserve=tpl_reserve,
    )
